wavegrid/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('architects.urls'))
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

architects/models.py
from django.db import models
from django.core.validators import FileExtensionValidator


# Create your models here.
class Projects(models.Model):
    title = models.CharField(max_length=100, null=True, blank=True)
    image = models.FileField(upload_to='images', null=True, blank=True)
    video = models.FileField(upload_to='videos', null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    client = models.CharField(max_length=300, null=True, blank=True)
    completed = models.BooleanField(default=True)


    def __str__ (self):
        return self.title

    class Meta:
        verbose_name_plural = 'Projects'
        ordering = ('-id',)    
        

class ProjectImages(models.Model):
    project = models.ForeignKey(Projects, on_delete=models.CASCADE) 
    image = models.ImageField(upload_to='images', blank=True, null=True) 

    def __str__ (self):
        return self.project.title


    class Meta:
        verbose_name_plural = 'ProjectImages'
        ordering = ('-id',)
          

class Feedback(models.Model):
    name = models.CharField(max_length=200)
    testimony = models.TextField()
    image = models.ImageField(upload_to='images', default="", blank=True, null=True)


    def __str__ (self):
        return self.name    

    class Meta:
        verbose_name_plural= 'Feedbacks'
        ordering = ('-id',)       

class Contact(models.Model):
    name = models.CharField(max_length=300, null=True, blank=True)
    email = models.CharField(max_length=300)
    message = models.TextField()

    def __str__ (self):
        return self.name

    class Meta:
        ordering = ('-id',) 

class Partners(models.Model):
    image = models.FileField(upload_to='images', null=True, blank=True)          

   

templates/admin-partners.html
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" 
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://use.fontawesome.com/2d80d2893d.js"></script>
    <title>Wavegrid Admin|partners</title>
</head>
<body>
  <nav class="navbar navbar-light bg-light fixed-top ">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'admin' %}">Admin site</a>
    </div>
  </nav>
  <div class="container">

    <!-- ALL FEEDBACKS WITH DELETE OPTION ONLY -->
    <div class="mt-2 mb-3">
      <h3 class="text-center">All Partners</h3>
    </div>
    <div class="row mb-4 mt-3">

       
          {% for partner in company_obj %}
          <div class="col-lg-3">
              <div class="card mt-2 mb-2">
                  <div class="card-body">
                      <img src="{{partner.image.url}}" alt="" style="height: 100px; width: 200px;">
                  </div> 
                  <div>
                    <a class="btn btn-outline-danger btn-lg ml-2 mb-2" href="{% url 'deletePartner' partner.id%}">Delete</a>
                  </div>   
              </div>
            </div>
          {% endfor %}
        
      </div>
      <nav class="d-flex justify-content-center wow fadeIn">  
        <ul class="pagination pg-blue">
          {% if company_obj.has_previous %}  
            <li class="page-item ">
              <a class="page-link" href="?page={{ company_obj.previous_page_number }}" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
                <span class="sr-only">Previous</span>
              </a>
            </li>
          {% endif %}
            <li class="page-item active">
              <a class="page-link" >{{ company_obj.number }}
                <span class="sr-only">(current)</span>
              </a>
            </li>
          {% if company_obj.has_next %}  
            <li class="page-item">
              <a class="page-link" href="?page={{ company_obj.next_page_number }}" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
                <span class="sr-only">Next</span>
              </a>
            </li>
          {% endif %}
        </ul>
      </nav>
    <!-- FORM FOR ADDING NEW PROJECTS -->
    <div class="row mb-4 mt-3">
      <div class="col">
        <div class="card-body mt-4 mb-4">
          <form method="post" enctype="multipart/form-data">
              {% csrf_token %}
              <div class="form-group">
                  {{ partners|crispy }}
              </div>
              <div class="form-actions">
                  <button class="btn btn-lg btn-secondary" type="submit">Add Partner</button>
              </div>
          </form>
  </div>
      </div>

      </div> 
      <!-- TABLE FOR DISPLAYING PROJECTS FROM DATABASE -->



<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

templates/admin-update-projects.html
{% load static %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{% static 'static/css/main.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" 
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css">
    <script src="https://use.fontawesome.com/2d80d2893d.js"></script>
    <title>Admin|Update prortfolio</title>
</head>
<body>
    <nav class="navbar navbar-light bg-light fixed-top ">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'admin' %}">Main site</a>
        </div>
      </nav>>
    <div class="container mt-3 mb-3">
        <div class="row mt-2 mb-3">
            <div class="col">
                <h4 class="mt-4 mb-2">Update a product</h4>
                <div class="card-body mt-4 mb-4">
                    <form method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            {{ form|crispy }}
                        </div>
                        <div class="form-actions">
                            <button class="btn btn-lg btn-secondary" type="submit">Save</button>
                        </div>
                    </form>
                </div>
            </div>
            </div>
            </div>

<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

templates/admin.html
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" 
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://use.fontawesome.com/2d80d2893d.js"></script>
    <title>Wavegrid Admin</title>
</head>
<body>
  <nav class="navbar navbar-light bg-light fixed-top ">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'home' %}">Main site</a>
    </div>
  </nav>
  <div class="container">
    
    <!-- ALL MESSAGES WITH DELETE OPTION ONLY -->
    <div class="mt-5 mb-3"> <h3 class="text-center">All messages</h3></div>
    <div class="row mb-4 mt-3">
     
       
          {% for message in page_obj %}
          <div class="col-lg-4">
              <div class="card mt-2 mb-2">
                  <div class="card-body">
                      <h5 class="text-uppercase text-small card-text"><b>FROM: </b>{{ message.name}}</h5>
                      <h5 class="card-text"><b>EMAIL: </b>{{ message.email }}</h5>
                      <p class="card-text"><b>MESSAGE: </b>{{ message.message}}</p>
                  </div> 
                  <div>
                    <a class="btn btn-outline-danger btn-lg ml-2 mb-2" href="{% url 'delete-message' message.id %}">Delete</a>
                  </div>   
              </div>
            </div>
          {% endfor %}
       
      </div>
      <nav class="d-flex justify-content-center wow fadeIn">  
        <ul class="pagination pg-blue">
          {% if page_obj.has_previous %}  
            <li class="page-item ">
              <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
                <span class="sr-only">Previous</span>
              </a>
            </li>
          {% endif %}
            <li class="page-item active">
              <a class="page-link" >{{ page_obj.number }}
                <span class="sr-only">(current)</span>
              </a>
            </li>
          {% if page_obj.has_next %}  
            <li class="page-item">
              <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
                <span class="sr-only">Next</span>
              </a>
            </li>
          {% endif %}
        </ul>
      </nav>
    <!-- ALL FEEDBACKS WITH DELETE OPTION ONLY -->
    <div class="mt-2 mb-3">
      <h3 class="text-center">All Testimonies</h3>
    </div>
    <div class="row mb-4 mt-3">

       
          {% for feedback in feedback_obj %}
          <div class="col-lg-4">
              <div class="card mt-2 mb-2">
                  <div class="card-body">
                      <h5 class="text-uppercase text-small card-text"><b>FROM: </b>{{ feedback.name}}</h5>
                      <p class="card-text"><b>Testimony: </b>{{ feedback.testimony}}</p>
                  </div> 
                  <div>
                    <a class="btn btn-outline-danger btn-lg ml-2 mb-2" href="{% url 'delete-feedback' feedback.id %}">Delete</a>
                  </div>   
              </div>
            </div>
          {% endfor %}
        
      </div>
      <nav class="d-flex justify-content-center wow fadeIn">  
        <ul class="pagination pg-blue">
          {% if feedback_obj.has_previous %}  
            <li class="page-item ">
              <a class="page-link" href="?page={{ feedback_obj.previous_page_number }}" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
                <span class="sr-only">Previous</span>
              </a>
            </li>
          {% endif %}
            <li class="page-item active">
              <a class="page-link" >{{ feedback_obj.number }}
                <span class="sr-only">(current)</span>
              </a>
            </li>
          {% if feedback_obj.has_next %}  
            <li class="page-item">
              <a class="page-link" href="?page={{ feedback_obj.next_page_number }}" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
                <span class="sr-only">Next</span>
              </a>
            </li>
          {% endif %}
        </ul>
      </nav>
    <!-- FORM FOR ADDING NEW PROJECTS -->
    <div class="row mb-4 mt-3">
      <div class="col-md-6">
        <div class="card-body mt-4 mb-4">
          <form method="post" enctype="multipart/form-data">
              {% csrf_token %}
              <div class="form-group">
                  {{ form|crispy }}
              </div>
              <div class="form-actions">
                  <button class="btn btn-lg btn-secondary" type="submit">Add Project</button>
              </div>
          </form>
  </div>
      </div>
      <div class="col-md-6 text-center">
        <div class="card-body mt-4 mb-4">
              <div>
                <a href="{% url 'adminpartners' %}">
                  <button class="btn btn-lg btn-info" type="submit">Operate on Partners</button></a>
              </div>
  </div>
      </div>

      </div> 
      <!-- TABLE FOR DISPLAYING PROJECTS FROM DATABASE -->
      <div class="table-responsive">
                <table class="table table-sm table-striped table-hover">
                  <thead class=" thead-dark">
                    <tr>
                      <th scope="col">Image</th>
                      <th scope="col">Title</th>
                      <th scope="col">Status
                      </th>
                      <th scope="col">Update</th>
                      <th scope="col">Delete</th>
                    </tr>
                  </thead>
                  <tbody>
                    {% for item in items %}
                      <tr>
                        <th scope="row">
                          {% if item.video and not item.image %}
                              <video autoplay muted loop
                              style="height: 70px; width: 70px;">
                                  <source src="{{item.video.url}}" type="video/mp4" class="rounded small-img" >
                              </video>
                          {% elif item.image and not item.video %}    
                              <img src="{{item.image.url}}" alt=""  class="img-fluid rounded small-img" style="height: 70px; width: 70px;">
                          {% elif item.image and item.video %}  
                            <img src="{{item.image.url}}" alt=""  class="img-fluid rounded small-img" style="height: 70px; width: 70px;">    
                          {% endif %}
                          
                        </th>
                          <td>{{item.title}}</td>
                          {% if item.completed == True%}
                            <td>Completed</td>
                          {% else %} 
                           <td>Ongoing</td>
                          {% endif %}
                          <td><a class="btn btn-info btn-sm" href="{% url 'update_project' item.id %}">Update</a></td>
                          <td><a class="btn btn-danger btn-sm" href="{% url 'delete-project' item.id %}">Delete</a></td>
                          </tr>
                
                    {% endfor %}
                  </tbody>
                  </table>  
                  <div>
                    <div class="pagination align-items-center justify-content-center">
                      <span class="step-links">
                          {% if items.has_previous %}                                     <!--If there is a previous page-->
                              <a class="btn btn-info btn-sm" href="?page={{ items.previous_page_number }}">&laquo;</a>  <!--Hyperlink to previous page on Click-->
                          {% endif %}
                  
                          <span class="current">
                               Page{{ items.number }} of {{ items.paginator.num_pages }}  <!--customers_list.number Is the current page number,customers_list.paginator.num_pages Is the total number of pages-->
                          </span>
                  
                          {% if items.has_next %}    <!--If there is a next page-->
                              <a class="btn btn-info btn-sm" href="?page={{ items.next_page_number }}">&raquo;</a>    <!--Hyperlink to next page when clicked-->
                          {% endif %}
                      </span>
                  </div> 
                </div>


<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" 
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css">
    <script src="https://use.fontawesome.com/2d80d2893d.js"></script>
    <title>Document</title>
</head>
<body>
    
    {% block content %}
    {% endblock content %}








    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    </body>
</html>

templates/contact.html
{% load crispy_forms_tags %}
<div class="container p-5">
    <h4 class=" text-center text-warning text-uppercase">Contact Us</h4>
    <div class="row mb-4 mt-3">
        <div class="card-body mt-4 mb-4">
          <form method="post" enctype="multipart/form-data">
              {% csrf_token %}
              <div class="form-group text-warning">
                  {{ form|crispy }}
              </div>
              <div class="form-actions">
                  <button class="btn btn-lg btn-warning" type="submit">Send message</button>
              </div>
          </form>
          </div>
  </div>

</div>

templates/partners.html
<div class="mb-3 mt-3 p-5">
    <div>
        <h4 class="text-center text-warning text-uppercase">OUR PARTNERS</h4>
        </div>
    <div class="row" style="flex-wrap: wrap;">

        {% for partner in partners %}
            <div class="card m-2">
                <div class="card-body">
                    <img src="{{partner.image.url}}" alt=""
                    style="box-shadow: rgba(0, 0, 0, 0.56) 0px 22px 80px 4px; width: 100px; height: 70px;">
                </div>
            </div>
            
        {% endfor %} 
       
            
       
    </div>
</div>

templates/project-details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" 
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css">
    <script src="https://use.fontawesome.com/2d80d2893d.js"></script>
    <title>Project Details</title>
</head>
<style>
  body
{
background: url('https://vip-go.shutterstock.com/blog/wp-content/uploads/sites/5/2020/05/shutterstock_359492192.jpg?w=750');
background-repeat: no-repeat;
background-attachment: fixed;
background-size: cover;
}

</style>
<body>
  <nav class="navbar navbar-expand-lg navbar-dark fixed-top scrolling-navbar">
    <div class="container">
      <a class="navbar-brand" href="{% url 'home' %}"><strong>HOME</strong></a>
        </div>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent-7"
        aria-controls="navbarSupportedContent-7" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent-7">
        <ul class="navbar-nav ml-auto">
          <!-- <li class="nav-item active">
            <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
          </li> -->
          <li class="nav-item active "><a class="nav-link" href="{% url 'all-projects' %}">Allprojects</a></li>
        </ul>
      </div>
      </nav>
    {% for project in projects %}
    {% if project.video and not project.image %}
    <video autoplay muted
    class="d-block w-100">
        <source src="{{project.video.url}}" type="video/mp4">
    </video>
{% elif project.image and not project.video %}    
    <img src="{{project.image.url}}" alt="" class="d-block w-100 img-fluid">
    {% elif project.image and project.video%}  
    <video autoplay muted
    class="d-block w-100">
        <source src="{{project.video.url}}" type="video/mp4">
    </video>  
    <div >
    <div class="col mt-2">
        <img src="{{project.image.url}}" alt="" class="img-fluid w-100">
    </div>
  </div>
{% endif %}    


<div class="p-5">
    <h5 class="text-uppercase text-center text-warning">Project details</h5>
<div class="card mb-4" style="box-shadow: rgba(0, 0, 0, 0.4) 0px 30px 90px;">
    <div class="card-body">
        <h1 class="card-text">{{project.title}}</h1>
        <p class="card-text">{{project.description}}</p>
        <p class="card-text">
          {% if project.completed %}

    <p class="text-success">completed</p>
{% else %}
    <p class="text-danger">Ongoing</p>    
{% endif %} 
        </p>
    </div>
</div>
<div class="container-fluid">
  <h5 class="text-uppercase text-center text-warning">Project Gallery</h5>
  <div class="row">
    {% for pi in project.projectimages_set.all %}  
    <div class="col-md-3 p-2 ">
      <img src="{{pi.image.url}}" class="img-fluid w-100" alt="" style="object-fit: contain;">
    </div>
    {% endfor %}
  </div>
</div>
</div>
    {% endfor %}

  

    <footer class="text-white text-center text-lg-start bg-dark">
        <!-- Grid container -->
        <div class="container p-4">
          <!--Grid row-->
          <div class="row mt-4">
            <!--Grid column-->
            <div class="col-lg-4 col-md-12 mb-4 mb-md-0">
              <h5 class="text-uppercase mb-4">About company</h5>
    
              <p>
                We are the waves to Grid your projects.
              </p>
    
              <p>
                Wavegrid architects is a visualization company founded in 2016 that has developed more than 
                1000 high quality renderings, images and animations 
                for clients in Kenya and around Africa.
              </p>
    
              <div class="mt-4">
                <!-- Facebook -->
                <a href="" target="blank"  type="button" class="btn btn-floating btn-lg text-white"><i class="fab fa-facebook-f"></i></a>
                <!-- Dribbble -->
                <a href="" target="blank"  type="button" class="btn btn-floating btn-lg text-white"><i class="fa fa-instagram"></i></a>
                <!-- Twitter -->
                <a href="" target="blank"  type="button" class="btn btn-floating btn-lg text-white"><i class="fab fa-twitter"></i></a>
                <!-- Google + -->
                <!-- Linkedin -->
              </div>
            </div>
            <!--Grid column-->
    
            <!--Grid column-->
            <div class="col-lg-4 col-md-6 mb-4 mb-md-0">
              <h5 class="text-uppercase mb-4 pb-1">Subscribe to Our Newsletter</h5>
    
              <div class="form-outline form-white mb-4">
                <input type="text" id="formControlLg" class="form-control form-control-lg" placeholder="Your Email" />
              </div>
    
              <ul class="list-unstyled fa-ul" style="margin-left: 1.65em;">
                <li class="mb-3">
                  <span class="fa-li"><i class="fas fa-home"></i></span><span class="ms-2">Nairobi, 00-967, Kenya</span>
                </li>
                <li class="mb-3">
                  <span class="fa-li"><i class="fas fa-envelope"></i></span><span class="ms-2">wavegridarchitects@gmail.com</span>
                </li>
                <li class="mb-3">
                  <span class="fa-li"><i class="fas fa-phone"></i></span><span class="ms-2">+ 254 707031397</span>
                </li>
              </ul>
            </div>
            <!--Grid column-->
    
            <!--Grid column-->
            <div class="col-lg-4 col-md-6 mb-4 mb-md-0">
              <h5 class="text-uppercase mb-4">Useful Links</h5>
              <ul class="list-unstyled mb-0">
                <li>About</li>
                <li>Services</li>
                <li>Portfolio</li>
                <li>Contact</li>
              </ul>
            </div>
            <!--Grid column-->
          </div>
          <!--Grid row-->
        </div>
        <!-- Grid container -->
    
        <!-- Copyright -->
        <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
          © 2021 Copyright:
          <a class="text-white" href="https://mdbootstrap.com/">Wavegrid Architects</a>
          <a class="text-white" href="https://vicdevs.herokuapp.com/" target="blank">Designed by Vicdevs</a>
        </div>
        <!-- Copyright -->
      </footer>
<!-- Footer -->
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>